config/routes.rb
SocialPigeon::Application.routes.draw do
  resources :senders

  root 'landing#index'
  get '/travellers/filter_results' => 'travellers#filter_results'
  resources :travellers

end

app/models/sender.rb
class Sender < ActiveRecord::Base
    validates :name,:email,:send_date_range , presence: true
end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
  validates :name,:email,:travel_date , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
  end

  # GET /senders/new
  def new
    @sender = Sender.new
  end

  # GET /senders/1/edit
  def edit
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = Sender.new(sender_params)

    respond_to do |format|
      if @sender.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sender }
      else
        format.html { render action: 'new' }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    @sender.destroy
    respond_to do |format|
      format.html { redirect_to senders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:name, :phone_number, :email, :address, :send_from, :send_to, :send_date_range, :item_description)
    end
end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
  before_action :set_traveller, only: [:show, :edit, :update, :destroy]

  # GET /travellers
  # GET /travellers.json
  def index
    @travellers = Traveller.all
  end

  # GET /travellers/1
  # GET /travellers/1.json
  def show
  end

  # GET /travellers/new
  def new
    @traveller = Traveller.new
  end

  # GET /travellers/1/edit
  def edit
  end

  # POST /travellers
  # POST /travellers.json
  def create
    @traveller = Traveller.new(traveller_params)

    respond_to do |format|
      if @traveller.save
        format.html { redirect_to @traveller, notice: 'Traveller was successfully created.' }
        format.json { render action: 'show', status: :created, location: @traveller }
      else
        format.html { render action: 'new' }
        format.json { render json: @traveller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travellers/1
  # PATCH/PUT /travellers/1.json
  def update
    respond_to do |format|
      if @traveller.update(traveller_params)
        format.html { redirect_to @traveller, notice: 'Traveller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @traveller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travellers/1
  # DELETE /travellers/1.json
  def destroy
    @traveller.destroy
    respond_to do |format|
      format.html { redirect_to travellers_url }
      format.json { head :no_content }
    end
  end
  
  
  
  def filter_results
    sender = Sender.find_by id: params[:id]
    @travellers = Traveller.where(:travelling_from => sender[:send_from], :travelling_to => sender[:send_to], :travel_date => Date.today .. (Date.today + sender[:send_date_range].days))
    
    @hash = {:sender => sender, :travellers => @travellers}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traveller
      @traveller = Traveller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traveller_params
      params.require(:traveller).permit(:name, :phone_number, :email, :address, :travelling_from, :travelling_to, :travel_date, :conditions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/views/landing/index.html.erb
<h1>Your parcel, delivered!</h1>
<p>
<a class="btn btn-lg btn-primary" href="/travellers/new">I am a Traveller</a>
<a class="btn btn-lg btn-primary" href="/senders/new">I am a Sender</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SocialPigeon</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<!-- Bootstrap -->
		<link href="/assets/css/bootstrap.css" rel="stylesheet">
	</head>
	<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SocialPigeon</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
	</br>
	</br>
	</br>
	</br>
    <div class="container">
		<%= yield %>
		<script src="/assets/js/bootstrap.js"></script>
	</div>
	</body>
</html>

app/views/senders/_form.html.erb
<%= form_for(@sender) do |f| %>
  <% if @sender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sender.errors.count, "error") %> prohibited this sender from being saved:</h2>

      <ul>
      <% @sender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :send_from %><br>
    <%= f.text_field :send_from %>
  </div>
  <div class="field">
    <%= f.label :send_to %><br>
    <%= f.text_field :send_to %>
  </div>
  <div class="field">
    <%= f.label :send_date_range %><br>
    <%= f.number_field :send_date_range %>
  </div>
  <div class="field">
    <%= f.label :item_description %><br>
    <%= f.text_field :item_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/senders/edit.html.erb
<h1>Editing sender</h1>

<%= render 'form' %>

<%= link_to 'Show', @sender %> |
<%= link_to 'Back', senders_path %>

app/views/senders/index.html.erb
<h1>Listing senders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Address</th>
      <th>Send from</th>
      <th>Send to</th>
      <th>Send date range</th>
      <th>Item description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @senders.each do |sender| %>
      <tr>
        <td><%= sender.name %></td>
        <td><%= sender.phone_number %></td>
        <td><%= sender.email %></td>
        <td><%= sender.address %></td>
        <td><%= sender.send_from %></td>
        <td><%= sender.send_to %></td>
        <td><%= sender.send_date_range %></td>
        <td><%= sender.item_description %></td>
        <td><%= link_to 'Show', sender %></td>
        <td><%= link_to 'Edit', edit_sender_path(sender) %></td>
        <td><%= link_to 'Destroy', sender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sender', new_sender_path %>

app/views/senders/new.html.erb
<h1>New sender</h1>

<%= render 'form' %>

app/views/senders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sender.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @sender.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sender.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @sender.address %>
</p>

<p>
  <strong>Send from:</strong>
  <%= @sender.send_from %>
</p>

<p>
  <strong>Send to:</strong>
  <%= @sender.send_to %>
</p>

<p>
  <strong>Send date range:</strong>
  <%= @sender.send_date_range %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @sender.item_description %>
</p>

<%= link_to 'Edit', edit_sender_path(@sender) %> |
<%= link_to 'Look for Traveller', {:controller => "travellers", :action => "filter_results", :id => @sender.id} %>

app/views/travellers/_form.html.erb
<%= form_for(@traveller) do |f| %>
  <% if @traveller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traveller.errors.count, "error") %> prohibited this traveller from being saved:</h2>

      <ul>
      <% @traveller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :travelling_from %><br>
    <%= f.text_field :travelling_from %>
  </div>
  <div class="field">
    <%= f.label :travelling_to %><br>
    <%= f.text_field :travelling_to %>
  </div>
  <div class="field">
    <%= f.label :travel_date %><br>
    <%= f.date_select :travel_date %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br>
    <%= f.text_field :conditions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travellers/edit.html.erb
<h1>Editing traveller</h1>

<%= render 'form' %>

<%= link_to 'Show', @traveller %> |
<%= link_to 'Back', travellers_path %>

app/views/travellers/filter_results.html.erb
<h1>Found following travellers</h1>
<h3>travelling from <%= @hash[:sender][:send_from]%> to <%= @hash[:sender][:send_to]%> in the next <%= @hash[:sender][:send_date_range]%> days</h3>
<table  class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Travel date</th>
      <th>Conditions</th>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @hash[:travellers].each do |traveller| %>
      <tr>
        <td><%= traveller.name %></td>
        <td><%= traveller.travel_date %></td>
        <td><%= traveller.conditions %></td>
        <td><%= link_to 'Show', traveller %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/travellers/index.html.erb
<h1>Listing travellers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Address</th>
      <th>Travelling from</th>
      <th>Travelling to</th>
      <th>Travel date</th>
      <th>Conditions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @travellers.each do |traveller| %>
      <tr>
        <td><%= traveller.name %></td>
        <td><%= traveller.phone_number %></td>
        <td><%= traveller.email %></td>
        <td><%= traveller.address %></td>
        <td><%= traveller.travelling_from %></td>
        <td><%= traveller.travelling_to %></td>
        <td><%= traveller.travel_date %></td>
        <td><%= traveller.conditions %></td>
        <td><%= link_to 'Show', traveller %></td>
        <td><%= link_to 'Edit', edit_traveller_path(traveller) %></td>
        <td><%= link_to 'Destroy', traveller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traveller', new_traveller_path %>

app/views/travellers/new.html.erb
<h1>New traveller</h1>

<%= render 'form' %>

app/views/travellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @traveller.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @traveller.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @traveller.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @traveller.address %>
</p>

<p>
  <strong>Travelling from:</strong>
  <%= @traveller.travelling_from %>
</p>

<p>
  <strong>Travelling to:</strong>
  <%= @traveller.travelling_to %>
</p>

<p>
  <strong>Travel date:</strong>
  <%= @traveller.travel_date %>
</p>

<p>
  <strong>Conditions:</strong>
  <%= @traveller.conditions %>
</p>

<%= link_to 'Edit', edit_traveller_path(@traveller) %> |